using System;
using System.Collections.Generic;
using System.Text;
using PromtTranslation.Domain.Models;

namespace PromtTranslation.Dtl.NewFolder
{
    public class AutoGeneratedData
    {
        private readonly Dictionary<string, Guid> _languageGuidsDictionary;
        public AutoGeneratedData(Dictionary<string, Guid> languageGuidsDictionary) =>
            (_languageGuidsDictionary) = (languageGuidsDictionary);
        public List<StatusModel> GenerateStatusOnAdd() 
        {
            return new List<StatusModel>()
            {
                new StatusModel {StatusValue = "Добавлен", Id = Guid.NewGuid()},
                new StatusModel {StatusValue = "Обрабатывается", Id = Guid.NewGuid()},
                new StatusModel {StatusValue = "Обравботан", Id = Guid.NewGuid()}
            };
        }
        public List<LanguageRouteStepsModel>GetRouteSteps() 
        {
            return new List<LanguageRouteStepsModel>
                    {
                        new LanguageRouteStepsModel
                        {
                            Id = Guid.NewGuid(),
                            LanguageFrom = "ru",
                            LanguageTo = "en",
                            RouteId = _languageGuidsDictionary["ru"]
                        },
                        new LanguageRouteStepsModel
                        {
                            Id = Guid.NewGuid(),
                            LanguageFrom = "ru",
                            LanguageTo = "fr",
                            RouteId = _languageGuidsDictionary["ru"]
                        },
                        new LanguageRouteStepsModel
                        {
                            Id = Guid.NewGuid(),
                            LanguageFrom = "ru",
                            LanguageTo = "it",
                            RouteId = _languageGuidsDictionary["ru"]
                        },
                        new LanguageRouteStepsModel
                        {
                            Id = Guid.NewGuid(),
                            LanguageFrom = "en",
                            LanguageTo = "da",
                            RouteId = _languageGuidsDictionary["ru"]
                        },
                        new LanguageRouteStepsModel
                        {
                            Id = Guid.NewGuid(),
                            LanguageFrom = "en",
                            LanguageTo = "ru",
                            RouteId = _languageGuidsDictionary["en"]
                        },
                        new LanguageRouteStepsModel
                        {
                            Id = Guid.NewGuid(),
                            LanguageFrom = "en",
                            LanguageTo = "da",
                            RouteId = _languageGuidsDictionary["en"]
                        },
                        new LanguageRouteStepsModel
                        {
                            Id = Guid.NewGuid(),
                            LanguageFrom = "en",
                            LanguageTo = "fr",
                            RouteId = _languageGuidsDictionary["en"]
                        },
                        new LanguageRouteStepsModel
                        {
                            Id = Guid.NewGuid(),
                            LanguageFrom = "en",
                            LanguageTo = "it",
                            RouteId = _languageGuidsDictionary["en"]
                        },
                        new LanguageRouteStepsModel
                        {
                            Id = Guid.NewGuid(),
                            LanguageFrom = "fr",
                            LanguageTo = "ru",
                            RouteId = _languageGuidsDictionary["fr"]

                        },
                        new LanguageRouteStepsModel
                        {
                            Id = Guid.NewGuid(),
                            LanguageFrom = "fr",
                            LanguageTo = "en",
                            RouteId = _languageGuidsDictionary["fr"]
                        },
                        new LanguageRouteStepsModel
                        {
                            Id = Guid.NewGuid(),
                            LanguageFrom = "fr",
                            LanguageTo = "it",
                            RouteId = _languageGuidsDictionary["fr"]
                        },
                        new LanguageRouteStepsModel
                        {
                            Id = Guid.NewGuid(),
                            LanguageFrom = "fr",
                            LanguageTo = "da",
                            RouteId = _languageGuidsDictionary["fr"]
                        },
                        new LanguageRouteStepsModel
                        {
                            Id = Guid.NewGuid(),
                            LanguageFrom = "it",
                            LanguageTo = "ru",
                            RouteId = _languageGuidsDictionary["it"]
                        },
                        new LanguageRouteStepsModel
                        {
                            Id = Guid.NewGuid(),
                            LanguageFrom = "it",
                            LanguageTo = "en",
                            RouteId = _languageGuidsDictionary["it"]
                        },
                        new LanguageRouteStepsModel
                        {
                            Id = Guid.NewGuid(),
                            LanguageFrom = "it",
                            LanguageTo = "fr",
                            RouteId = _languageGuidsDictionary["it"]
                        },
                        new LanguageRouteStepsModel
                        {
                            Id = Guid.NewGuid(),
                            LanguageFrom = "it",
                            LanguageTo = "da",
                            RouteId = _languageGuidsDictionary["it"]
                        },
                         new LanguageRouteStepsModel
                        {
                            Id = Guid.NewGuid(),
                            LanguageFrom = "da",
                            LanguageTo = "en",
                            RouteId = _languageGuidsDictionary["da"]
                        },
                        new LanguageRouteStepsModel
                        {
                            Id = Guid.NewGuid(),
                            LanguageFrom = "da",
                            LanguageTo = "it",
                            RouteId = _languageGuidsDictionary["da"]
                        },
                        new LanguageRouteStepsModel
                        {
                            Id = Guid.NewGuid(),
                            LanguageFrom = "da",
                            LanguageTo = "fr",
                            RouteId = _languageGuidsDictionary["da"]
                        },
                        new LanguageRouteStepsModel
                        {
                            Id = Guid.NewGuid(),
                            LanguageFrom = "en",
                            LanguageTo = "ru",
                            RouteId = _languageGuidsDictionary["da"]
                        }
                    };
        }
        public List<RouteModel> GetRoutes() 
        {

            return new List<RouteModel>()
            {
                new RouteModel
                {
                    Id = _languageGuidsDictionary["ru"],
                    RouteName = "ru"
                },
                new RouteModel
                {
                    Id = _languageGuidsDictionary["en"],
                    RouteName = "en",
                },
                new RouteModel
                {
                    Id = _languageGuidsDictionary["fr"],
                    RouteName = "fr",
                },
                new RouteModel
                {
                    Id = _languageGuidsDictionary["it"],
                    RouteName = "it",
                },
                new RouteModel
                {
                    Id = _languageGuidsDictionary["da"],
                    RouteName = "da",
                },
            };
        }
    }
}
